version: '3.1'

services:
  database:
    image: postgres:11.5
    container_name: task-management-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    restart: always
