spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
